version: '3'
services:
  opennre:
    build: ./
    stdin_open: true
    tty: true
    command: uvicorn api_service:app --host 0.0.0.0 --port 4000 --reload
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
      CUDA_VISIBLE_DEVICES: 0
    ulimits:
      memlock: -1
    shm_size: '16gb'
    volumes:
      - .:/opennre
    ports:
      - 4000:4000
    networks:
      - backend

  entitylinking:
    build:
      context: /home/daniel/projects/entity-linking/entitylinking/app
      dockerfile: Dockerfile
    command: /opt/conda/envs/aida_coreference/bin/uvicorn api_service:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - /home/daniel/projects/entity-linking/entitylinking/app:/app
    ports:
      - 5000:5000
    networks:
      - backend

  entitylinking_elasticsearch:
    image: laituan245/wikidata-es
    environment:
      - discovery.type=single-node
    # ports:
    #   - 9201:9200
    networks:
        - backend

  neo4j:
    # runtime: nvidia
    build: ./neo4j/
    stdin_open: true
    tty: true
    environment:
      - NEO4J_AUTH=${NEO4J_PASSWORD}
    volumes:
      - ./neo4j/src:/src
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
    ports:
      - 7687:7687
      - 7474:7474
    ulimits:
      memlock: -1 # set upper limit for how much memory is locked for the container (-1 means lock as much as the container uses)
    shm_size: 32gb # set upper limit for how much shared memory container can use
    networks:
        - backend

volumes:
  storage:
    driver: local

networks:  
  backend: 
